__module_name__ = "xchat-speak"
__module_version__ = "1.0"
__module_description__ = "speak using festival"

import socket
import os
import time
import atexit
import signal
import xchat
import string

class festival:
	"Festival object"
	
	def __init__(self):
		self.sock = self.open()
		
	def _checkresp(self):
		if self.sock.recv(256)=='ER\n':
			raise Exception
	
	def set_param(self,param,value):
		"Set parameter to a number or a symbol."
		
		if type(value) is str:
			self.sock.send("(Parameter.set '%s '%s)"%(param,value))
		else:
			self.sock.send("(Parameter.set '%s %r)"%(param,value))
		self._checkresp()

	def set_param_str(self,param,value):
		"Set parameter to a string."
		
		self.sock.send("(Parameter.set '%s \"%s\")"%(param,value))
		self._checkresp()
			
	def block(self,flag=True):
		"Sets blocking/nonblocking mode."
		
		if flag:
			self.sock.send("(audio_mode 'sync)")
		else:
			self.sock.send("(audio_mode 'async)")
		self._checkresp()
	
	def set_audio_method(self,method=None,device=None):
		"Set audio method and/or device."
		
		if method is not None:
			self.set_param('Audio_Method',method)
		if device is not None:
			self.set_param_str('Audio_Device',device)
	
	def set_audio_command(self,command,rate=None,format=None):
		"""Set audio command, and optionally rate and format.
		
		Sets audio method to "Audio_Command"."""
		
		self.set_audio_method("Audio_Command")
		if rate is not None:
			self.set_param('Audio_Required_Rate',rate)
		if format is not None:
			self.set_param('Audio_Required_Format',format)
		self.set_param_str('Audio_Command',command)
		
	def say(self,text):
		"Speak string 'text'."
                self.open()
		self.sock.send('(SayText "%s")'%text)
                # this makes xchat block while speaking. bad.
		#self._checkresp()
		
	def sayfile(self,filename):
		"""Speak contents of file 'filename'.
		
		Note that this is done on the server end, not the client
		end, so you best pass it absolute filenames."""
		
		self.sock.send('(tts "%s" nil)'%filename)
		self._checkresp()
		
	def close(self):
		"Terminate the Festival connection."
		self.sock.send('(quit)')

        def open(self,host='',port=1314,nostart=False):
        	"""Opens a new connection to a Festival server.
	
        	Attempts to connect to a Festival server (most likely started with
        	'festival --server'). Will attempt to start a local server on port
        	1314 if one is not running and the 'nostart' flag is not set to
        	True. Returns a festival.festival object."""
	
        	global festival_pid
                from subprocess import STDOUT, Popen
	
	        sock=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
	        try:
	        	sock.connect((host,port))
	        except socket.error:
	        	if nostart:
	        		raise socket.error
	        	else:
                                #festival_pid = Popen(["festival", "--server"],stdout=3,stderr=STDOUT).pid 
                                festival_pid = Popen(["festival", "--server"]).pid 
		        	atexit.register(self._kill_server)
		        	for t in xrange(20):
		        		try:
		        			time.sleep(.25)
		        			sock.connect((host,port))
		        		except socket.error:
		        			pass
		        		else:
		        			break
		        	else:
		        		raise socket.error
		
	        self.sock = sock
                return sock

        def _kill_server():
        	os.kill(festival_pid,signal.SIGTERM)

class wordcleanser:
  def __init__(self):
    self.abbr = {'..' : '\,',
        '^' : 'look up',
        '...' : '\,',
        '2nd' : 'second',
        '31337' : 'eleet',
        '56k' : '56 k',
        ':)' : 'smiles',
        ':-)' : 'smiles',
        ':-p' : 'sticks tongue out',
        ':>' : 'smiles',
        ':p' : 'sticks tongue out',
        ';)' : 'winks',
        ';-)' : 'winks',
        'aamof' : 'as a matter of fact',
        'ad' : 'add',
        'adn' : 'any day now',
        'afaik' : 'as far as i know',
        'afair' : 'as far as i remember',
        'afj' : 'april fool\'s joke',
        'afk' : 'away from the keyboard',
        'asap' : 'as soon as possible',
        'at0mic_' : 'atomic',
        'atm' : 'at the moment',
        'awc' : 'after while, crocodile',
        'awgthtgtwta?' : 'are we going to have to go through with this again?',
        'ayt' : 'are you there?',
        'b4' : 'before',
        'b4n' : 'bye for now',
        'bak' : 'back at keyboard',
        'bakerw0rk' : 'baker-work',
        'bbfn' : 'bye bye for now',
	'bbiab' : 'be back in a bit',
        'bbiaf' : 'be back in a few',
        'bbialb' : 'be back in a little bit',
        'bbl' : 'be back later',
        'bcnu' : 'be seeing you',
        'bf' : 'boy friend',
        'brb' : 'be right back',
        'bta' : 'but then again',
        'btw' : 'by the way',
        'bye?' : 'are you ready to say goodbye',
        'bykt' : 'but you knew that',
        'byob' : 'bring your own bottle',
        'byom' : 'bring your own mac',
        'cmiiw' : 'correct me if i\'m wrong',
        'cu' : 'see you',
        'cul' : 'see you later',
        'cul8r' : 'see you later',
        'cula' : 'see you later, alligator',
        'cya' : 'see ya',
        'd/l' : 'download',
        'd00d' : 'dood',
        'diku?' : 'do i know you?',
        'dtrt' : 'do the right thing',
	'dvd' : 'd v d',
        'esad' : 'eat shit and die',
        'f2f' : 'face to face',
        'fcfs' : 'first come, first served',
        'fitb' : 'fill in the blank',
        'flyaway' : 'fly away',
        'foad' : 'feck off and die',
        'foaf' : 'friend of a friend',
        'freebsd' : 'free bsd',
        'fs' : 'for sale',
        'fubar' : 'fecked up beyond all repair',
        'fud' : 'fear, uncertainty and doubt',
        'fwiw' : 'for what it\'s worth',
        'fya' : 'for your amusement',
        'fyi' : 'for your information',
        'ga' : 'go ahead',
        'gal' : 'get a life',
        'gb' : 'gigabytes',
        'gd\&r' : 'grinning, ducking and running',
        'gd\&wvvf' : 'grinning, ducking, and walking very, very fast',
        'gf' : 'girl friend',
        'giwist' : 'gee, i wish i\'d said that',
        'gmta' : 'great minds think alike',
        'hhoj' : 'ha ha only joking',
        'hhok' : 'ha ha only kidding',
        'hhos' : 'ha ha only serious',
	'hmm' : 'hurrmmm',
        'hoyew' : 'hanging on your every word',
        'hp/ux' : 'hp ux',
        'hrm' : 'herm',
        'hth' : 'hope that helps!',
        'i8urdog' : 'I ate your dog',
        'iac' : 'in any case',
        'ianal' : 'i am not a lawyer',
        'iaw' : 'in accordance with',
        'ic' : 'i see',
        'identd' : 'ident d',
        'iirc' : 'if i remember correctly',
        'ijwtk' : 'i just want to know',
        'ijwts' : 'i just want to say',
        'ikwum' : 'i know what you mean',
        'ima' : 'i might add',
        'imao' : 'in my arrogant opinion',
        'imco' : 'in my considered opinion',
        'ime' : 'in my experience',
        'imho' : 'in my humble opinion',
        'imnsho' : 'in my not so humble opinion',
        'imo' : 'in my opinion',
        'inpo' : 'in no particular order',
	'irq' : 'i r q',
        'iow' : 'in other words',
        'ip' : 'i p',
        'ipx' : 'i p x',
        'irl' : 'in real life',
	'isdn' : 'i s d n',
        'iss' : 'i\'m so sure',
        'issygti' : 'i\'m so sure you get the idea!',
        'iswim' : 'if you see what i mean',
        'iwbni' : 'it would be nice if',
        'iyfeg' : 'insert your favorite ethnic group',
        'iyswim' : 'if you see what i mean',
        'jam' : 'just a minute',
        'jic' : 'just in case',
        'k3nny' : 'kenny',
        'kb' : 'kilobytes',
        'kibo' : 'knowledge in, bullshit out',
        'kwim' : 'know what i mean?',
        'kyfc' : 'keep your fingers crossed',
        'l8r' : 'later',
        'lin0x' : 'linux',
        'ljbf' : 'let\'s just be friends',
        'lol' : 'laughing out loud',
        'lshmba' : 'laughing so hard my belly aches',
        'lthtt' : 'laughing too hard to type',
        'ltns' : 'long time no see',
        'mb' : 'megabytes',
        'motas' : 'member of the appropriate sex',
        'motd' : 'message of the day',
        'motos' : 'member of the opposite sex',
        'motss' : 'member of the same sex',
        'msg' : 'message',
        'myob' : 'mind your own business',
        'n-tropy' : 'entropy',
        'nah' : 'no',
        'ne1' : 'anyone',
        'netbsd' : 'net bsd',
        'nhoh' : 'never heard of him slash her',
        'np' : 'no problem',
        'obo' : 'or best offer',
        'obtw' : 'oh, by the way',
        'oic' : 'oh, i see',
        'ok' : 'o k',
        'openbsd' : 'open bsd',
        'otf' : 'on the floor',
        'otfl' : 'on the floor laughing',
        'otoh' : 'on the other hand',
        'ott' : 'over the top',
        'pci' : 'p c i',
        'pmf' : 'pardon my french',
        'pmfbi' : 'pardon me for butting in',
        'pmfji' : 'pardon me for jumping in',
        'pmji' : 'pardon my jumping in',
        'pncah' : 'please, no cursing allowed here',
        'pnpisa' : 'p n p i s a',
        'po0p' : 'poop',
        'ppl' : 'people',
	'pstn' : 'p s t n',
        'ptmm' : 'please tell me more',
        'quazwork' : 'quaz-work',
        'r u there?' : 'are you there?',
        're' : 'regreet',
        'redhat' : 'red hat',
        'rehi' : 'hi again',
        'rl' : 'real life',
        'rotf' : 'rolling on the floor',
        'rotfl' : 'rolling on the floor laughing',
        'rotflol' : 'rolling on the floor laughing out loud',
        'rsn' : 'real soon now',
        'rsvp' : 'please reply',
        'rtbm' : 'read the bloody manual',
        'rtfaq' : 'read the frequently asked questions',
        'rtfm' : 'read the fecking manual',
        'rtm' : 'read the manual',
        'ryfm' : 'read your friendly manual',
        'scsi' : 'scuzy',
        'sec' : 'wait a second',
        'secs' : 'seconds',
        'snafu' : 'situation normal, all fouled up',
        'sol' : 'shit out of luck',
        'sos' : 'help!',
        'swim' : 'see what i mean?',
        'tafn' : 'that\'s all for now',
        'tanj' : 'there ain\'t no justice',
        'tanstaafl' : 'there ain\'t no such thing as a free lunch',
        'tcp' : 't c p',
        'thankx' : 'thanks',
        'thx' : 'thanks',
        'tia' : 'thanks in advance',
        'tic' : 'tongue in cheek',
        'tntl' : 'trying not to laugh',
        'tnx' : 'thanks',
        'tnxe6' : 'thanks a million',
        'tptb' : 'the powers that be',
        'ttbomk' : 'to the best of my knowledge',
        'ttfn' : 'ta ta for now',
        'ttksf' : 'trying to keep a straight face',
        'ttyl' : 'talk to you later',
        'tyvm' : 'thank you very much',
        'uok' : 'are you ok?',
        'w/o' : 'without',
        'wb' : 'welcome back',
        'wdyt' : 'what do you think?',
        'wibni' : 'wouldn\t it be nice if',
        'willg' : 'will g',
        'wrt' : 'with regard to,  or with respect to',
        'wtb' : 'want to buy',
        'wtf' : 'what the feck',
        'wtg' : 'way to go!',
        'wtgp' : 'want to go private?',
        'wth' : 'what the hell?',
        'wygiswypf' : 'what you get is what you pay for',
        'xoxoxo' : 'kisses and hugs',
        'yaba' : 'yet another bloody acronym',
        'yaun' : 'yet another unix nerd',
        'ygti' : 'you get the idea?',
        'ygwypf' : 'you get what you pay for',
        'yiu' : 'yes, i understand',
        'yiwgp' : 'yes, i will go private',
        'ymmv' : 'your mileage may vary',
        'yt' : 'are you there',
        'Ameria' : 'America',
        'I\"m' : 'I\'m',
        'I\;d' : 'I\'d',
        'I\;ll' : 'I\'ll',}

    self.spell = {'abbout' : 'about',
        'abotu' : 'about',
        'abouta' : 'about a',
        'aboutit' : 'about it',
        'aboutthe' : 'about the',
        'abscence' : 'absence',
        'accesories' : 'accessories',
        'accidant' : 'accident',
        'accomodate' : 'accommodate',
        'accordingto' : 'according to',
        'accross' : 'across',
        'acheive' : 'achieve',
        'acheived' : 'achieved',
        'acheiving' : 'achieving',
        'acn' : 'can',
        'acommodate' : 'accommodate',
        'acomodate' : 'accommodate',
        'actualyl' : 'actually',
        'additinal' : 'additional',
        'addtional' : 'additional',
        'adequit' : 'adequate',
        'adequite' : 'adequate',
        'adn' : 'and',
        'advanage' : 'advantage',
        'affraid' : 'afraid',
        'afterthe' : 'after the',
        'againstt he' : 'against the',
        'aganist' : 'against',
        'aggresive' : 'aggressive',
        'agian' : 'again',
        'agreemeent' : 'agreement',
        'agreemeents' : 'agreements',
        'agreemnet' : 'agreement',
        'agreemnets' : 'agreements',
        'agressive' : 'aggressive',
        'ahppen' : 'happen',
        'ahve' : 'have',
        'allwasy' : 'always',
        'allwyas' : 'always',
        'almots' : 'almost',
        'almsot' : 'almost',
        'alomst' : 'almost',
        'alot' : 'a lot',
        'alraedy' : 'already',
        'alreayd' : 'already',
        'alreday' : 'already',
        'alwasy' : 'always',
        'alwats' : 'always',
        'alway' : 'always',
        'alwyas' : 'always',
        'amde' : 'made',
        'amke' : 'make',
        'amkes' : 'makes',
        'anbd' : 'and',
        'andone' : 'and one',
        'andt he' : 'and the',
        'andteh' : 'and the',
        'andthe' : 'and the',
        'anothe' : 'another',
        'anual' : 'annual',
        'apparant' : 'apparent',
        'apparrent' : 'apparent',
        'appearence' : 'appearance',
        'appeares' : 'appears',
        'applicaiton' : 'application',
        'applicaitons' : 'applications',
        'applyed' : 'applied',
        'appointiment' : 'appointment',
        'approrpiate' : 'appropriate',
        'approrpriate' : 'appropriate',
        'aquisition' : 'acquisition',
        'aquisitions' : 'acquisitions',
        'aren\;t' : 'aren\'t',
        'arguement' : 'argument',
        'arguements' : 'arguments',
        'arn\'t' : 'aren\'t',
        'arond' : 'around',
        'artical' : 'article',
        'articel' : 'article',
        'asdvertising' : 'advertising',
        'askt he' : 'ask the',
        'assistent' : 'assistant',
        'asthe' : 'as the',
        'atention' : 'attention',
        'atmospher' : 'atmosphere',
        'attentioin' : 'attention',
        'atthe' : 'at the',
        'audeince' : 'audience',
        'audiance' : 'audience',
        'availalbe' : 'available',
        'awya' : 'away',
        'aywa' : 'away',
        'bakc' : 'back',
        'balence' : 'balance',
        'ballance' : 'balance',
        'baout' : 'about',
        'bcak' : 'back',
        'beacuse' : 'because',
        'becasue' : 'because',
        'becaus' : 'because',
        'becausea' : 'because a',
        'becauseof' : 'because of',
        'becausethe' : 'because the',
        'becauseyou' : 'because you',
        'becomeing' : 'becoming',
        'becomming' : 'becoming',
        'becuase' : 'because',
        'becuse' : 'because',
        'befoer' : 'before',
        'beggining' : 'beginning',
        'begining' : 'beginning',
        'beginining' : 'beginning',
        'beleiev' : 'believe',
        'beleieve' : 'believe',
        'beleif' : 'belief',
        'beleive' : 'believe',
        'beleived' : 'believed',
        'beleives' : 'believes',
        'benifit' : 'benefit',
        'benifits' : 'benefits',
        'betwen' : 'between',
        'beutiful' : 'beautiful',
        'boxs' : 'boxes',
        'brodcast' : 'broadcast',
        'butthe' : 'but the',
        'bve' : 'be',
        'byt he' : 'by the',
        'caharcter' : 'character',
        'calcullated' : 'calculated',
        'calulated' : 'calculated',
        'can\'t of been' : 'can\'t have been',
        'can\;t' : 'can\'t',
        'candidtae' : 'candidate',
        'candidtaes' : 'candidates',
        'catagory' : 'category',
        'categiory' : 'category',
        'certian' : 'certain',
        'challange' : 'challenge',
        'challanges' : 'challenges',
        'chaneg' : 'change',
        'chanegs' : 'changes',
        'changable' : 'changeable',
        'changeing' : 'changing',
        'changng' : 'changing',
        'charachter' : 'character',
        'charachters' : 'characters',
        'charactor' : 'character',
        'charecter' : 'character',
        'charector' : 'character',
        'cheif' : 'chief',
        'chekc' : 'check',
        'chnage' : 'change',
        'cieling' : 'ceiling',
        'circut' : 'circuit',
        'claer' : 'clear',
        'claered' : 'cleared',
        'claerly' : 'clearly',
        'cliant' : 'client',
        'cna' : 'can',
        'colection' : 'collection',
        'comanies' : 'companies',
        'comany' : 'company',
        'comapnies' : 'companies',
        'comapny' : 'company',
        'combintation' : 'combination',
        'comited' : 'committed',
        'comittee' : 'committee',
        'commadn' : 'command',
        'comming' : 'coming',
        'commitee' : 'committee',
        'committe' : 'committee',
        'committment' : 'commitment',
        'committments' : 'commitments',
        'committy' : 'committee',
        'comntain' : 'contain',
        'comntains' : 'contains',
        'compair' : 'compare',
        'company\;s' : 'company\'s',
        'compleated' : 'completed',
        'compleatly' : 'completely',
        'compleatness' : 'completeness',
        'completly' : 'completely',
        'completness' : 'completeness',
        'composate' : 'composite',
        'comtain' : 'contain',
        'comtains' : 'contains',
        'comunicate' : 'communicate',
        'comunity' : 'community',
        'condolances' : 'condolences',
        'conected' : 'connected',
        'conferance' : 'conference',
        'confirmmation' : 'confirmation',
        'considerit' : 'considerate',
        'considerite' : 'considerate',
        'consonent' : 'consonant',
        'conspiricy' : 'conspiracy',
        'consultent' : 'consultant',
        'convertable' : 'convertible',
        'cooparate' : 'cooperate',
        'cooporate' : 'cooperate',
        'corproation' : 'corporation',
        'corproations' : 'corporations',
        'corruptable' : 'corruptible',
        'cotten' : 'cotton',
        'coudl' : 'could',
        'coudln\'t' : 'couldn\'t',
        'coudn\'t' : 'couldn\'t',
        'could of been' : 'could have been',
        'could of had' : 'could have had',
        'couldn\;t' : 'couldn\'t',
        'couldnt' : 'couldn\'t',
        'couldthe' : 'could the',
        'cpoy' : 'copy',
        'ctaegory' : 'category',
        'cusotmer' : 'customer',
        'cusotmers' : 'customers',
        'cutsomer' : 'customer',
        'cutsomers' : 'customers',
        'cxan' : 'can',
        'danceing' : 'dancing',
        'dcument' : 'document',
        'deatils' : 'details',
        'decison' : 'decision',
        'decisons' : 'decisions',
        'defendent' : 'defendant',
        'definately' : 'definitely',
        'deptartment' : 'department',
        'desicion' : 'decision',
        'desicions' : 'decisions',
        'desision' : 'decision',
        'desisions' : 'decisions',
        'develeoprs' : 'developers',
        'devellop' : 'develop',
        'develloped' : 'developed',
        'develloper' : 'developer',
        'devellopers' : 'developers',
        'develloping' : 'developing',
        'devellopment' : 'development',
        'devellopments' : 'developments',
        'devellops' : 'develop',
        'develope' : 'develop',
        'developement' : 'development',
        'developements' : 'developments',
        'developor' : 'developer',
        'developors' : 'developers',
        'develpment' : 'development',
        'diaplay' : 'display',
        'didint' : 'didn\'t',
        'didn\;t' : 'didn\'t',
        'didnot' : 'did not',
        'didnt' : 'didn\'t',
        'difefrent' : 'different',
        'diferences' : 'differences',
        'differance' : 'difference',
        'differances' : 'differences',
        'differant' : 'different',
        'differemt' : 'different',
        'differnt' : 'different',
        'diffrent' : 'different',
        'directer' : 'director',
        'directers' : 'directors',
        'directiosn' : 'direction',
        'disatisfied' : 'dissatisfied',
        'discoverd' : 'discovered',
        'disign' : 'design',
        'dispaly' : 'display',
        'dissonent' : 'dissonant',
        'distribusion' : 'distribution',
        'divsion' : 'division',
        'do\'nt' : 'don\'t',
        'docuement' : 'documents',
        'docuemnt' : 'document',
        'documetn' : 'document',
        'documnet' : 'document',
        'documnets' : 'documents',
        'doe snot' : 'does not',
        'doens\'t' : 'doesn\'t',
        'doese' : 'does',
        'doesn\;t' : 'doesn\'t',
        'doesnt' : 'doesn\'t',
        'doign' : 'doing',
        'doimg' : 'doing',
        'doind' : 'doing',
        'dollers' : 'dollars',
        'don\'t no' : 'don\'t know',
        'don\;t' : 'don\'t',
        'donig' : 'doing',
        'dont' : 'don\'t',
        'dosn\'t' : 'doesn\'t',
        'driveing' : 'driving',
        'drnik' : 'drink',
        'efel' : 'feel',
        'effecient' : 'efficient',
        'efort' : 'effort',
        'eforts' : 'efforts',
        'ehr' : 'her',
        'eligable' : 'eligible',
        'embarass' : 'embarrass',
        'enought' : 'enough',
        'equippment' : 'equipment',
        'equivalant' : 'equivalent',
        'esle' : 'else',
        'especally' : 'especially',
        'especialyl' : 'especially',
        'espesially' : 'especially',
        'excellant' : 'excellent',
        'excercise' : 'exercise',
        'exchagne' : 'exchange',
        'exchagnes' : 'exchanges',
        'excitment' : 'excitement',
        'exhcange' : 'exchange',
        'exhcanges' : 'exchanges',
        'experiance' : 'experience',
        'experienc' : 'experience',
        'exprience' : 'experience',
        'exprienced' : 'experienced',
        'eyt' : 'yet',
        'faeture' : 'feature',
        'faetures' : 'features',
        'familair' : 'familiar',
        'familar' : 'familiar',
        'familliar' : 'familiar',
        'fammiliar' : 'familiar',
        'feild' : 'field',
        'feilds' : 'fields',
        'fianlly' : 'finally',
        'fidn' : 'find',
        'finalyl' : 'finally',
        'firends' : 'friends',
        'firts' : 'first',
        'follwo' : 'follow',
        'follwoing' : 'following',
        'fora' : 'for a',
        'foriegn' : 'foreign',
        'forthe' : 'for the',
        'forwrd' : 'forward',
        'forwrds' : 'forwards',
        'foudn' : 'found',
        'foward' : 'forward',
        'fowards' : 'forwards',
        'freind' : 'friend',
        'freindly' : 'friendly',
        'freinds' : 'friends',
        'frmo' : 'from',
        'fromt he' : 'from the',
        'fromthe' : 'from the',
        'furneral' : 'funeral',
        'fwe' : 'few',
        'garantee' : 'guarantee',
        'gaurd' : 'guard',
        'gemeral' : 'general',
        'gerat' : 'great',
        'geting' : 'getting',
        'gettin' : 'getting',
        'gievn' : 'given',
        'giveing' : 'giving',
        'gloabl' : 'global',
        'goign' : 'going',
        'gonig' : 'going',
        'govenment' : 'government',
        'goverment' : 'government',
        'gruop' : 'group',
        'gruops' : 'groups',
        'grwo' : 'grow',
        'guidlines' : 'guidelines',
        'hadbeen' : 'had been',
        'hadn\;t' : 'hadn\'t',
        'haev' : 'have',
        'hapen' : 'happen',
        'hapened' : 'happened',
        'hapening' : 'happening',
        'hapens' : 'happens',
        'happend' : 'happened',
        'hasbeen' : 'has been',
        'hasn\;t' : 'hasn\'t',
        'hasnt' : 'hasn\'t',
        'havebeen' : 'have been',
        'haveing' : 'having',
        'haven\;t' : 'haven\'t',
        'hda' : 'had',
        'he\;ll' : 'he\'ll',
        'hearign' : 'hearing',
        'helpfull' : 'helpful',
        'herat' : 'heart',
        'here\;s' : 'here\'s',
        'hesaid' : 'he said',
        'hewas' : 'he was',
        'hge' : 'he',
        'hismelf' : 'himself',
        'hlep' : 'help',
        'hsa' : 'has',
        'hsi' : 'his',
        'hte' : 'the',
        'htere' : 'there',
        'htese' : 'these',
        'htey' : 'they',
        'hting' : 'thing',
        'htink' : 'think',
        'htis' : 'this',
        'hvae' : 'have',
        'hvaing' : 'having',
        'hwich' : 'which',
        'i snot' : 'is not',
        'idae' : 'idea',
        'idaes' : 'ideas',
        'identofy' : 'identify',
        'ihs' : 'his',
        'iits the' : 'it\'s the',
        'imediate' : 'immediate',
        'imediatly' : 'immediately',
        'immediatly' : 'immediately',
        'importent' : 'important',
        'importnat' : 'important',
        'impossable' : 'impossible',
        'improvemnt' : 'improvement',
        'improvment' : 'improvement',
        'includ' : 'include',
        'indecate' : 'indicate',
        'indenpendence' : 'independence',
        'indenpendent' : 'independent',
        'indepedent' : 'independent',
        'independance' : 'independence',
        'independant' : 'independent',
        'influance' : 'influence',
        'infomation' : 'information',
        'informatoin' : 'information',
        'inital' : 'initial',
        'instaleld' : 'installed',
        'insted' : 'instead',
        'insurence' : 'insurance',
        'int he' : 'in the',
        'inteh' : 'in the',
        'interum' : 'interim',
        'inthe' : 'in the',
        'inwhich' : 'in which',
        'isn\;t' : 'isn\'t',
        'isthe' : 'is the',
        'it snot' : 'it\'s not',
        'it\' snot' : 'it\'s not',
        'it\;ll' : 'it\'ll',
        'it\;s' : 'it\'s',
        'itis' : 'it is',
        'ititial' : 'initial',
        'itnerest' : 'interest',
        'itnerested' : 'interested',
        'itneresting' : 'interesting',
        'itnerests' : 'interests',
        'its a' : 'it\'s a',
        'its the' : 'it\'s the',
        'itwas' : 'it was',
        'iwll' : 'will',
        'iwth' : 'with',
        'jsut' : 'just',
        'jugment' : 'judgment',
        'knowldge' : 'knowledge',
        'knowlege' : 'knowledge',
        'knwo' : 'know',
        'knwon' : 'known',
        'knwos' : 'knows',
        'konw' : 'know',
        'konwn' : 'known',
        'konws' : 'knows',
        'labratory' : 'laboratory',
        'lastyear' : 'last year',
        'learnign' : 'learning',
        'lenght' : 'length',
        'let\'s him' : 'lets him',
        'let\'s it' : 'lets it',
        'let\;s' : 'let\'s',
        'levle' : 'level',
        'libary' : 'library',
        'librarry' : 'library',
        'librery' : 'library',
        'liek' : 'like',
        'liekd' : 'liked',
        'lieutenent' : 'lieutenant',
        'liev' : 'live',
        'likly' : 'likely',
        'lisense' : 'license',
        'littel' : 'little',
        'litttle' : 'little',
        'liuke' : 'like',
        'liveing' : 'living',
        'loev' : 'love',
        'lonly' : 'lonely',
        'lookign' : 'looking',
        'maintenence' : 'maintenance',
        'makeing' : 'making',
        'managment' : 'management',
        'mantain' : 'maintain',
        'marraige' : 'marriage',
        'may of been' : 'may have been',
        'may of had' : 'may have had',
        'memeber' : 'member',
        'merchent' : 'merchant',
        'mesage' : 'message',
        'mesages' : 'messages',
        'might of been' : 'might have been',
        'might of had' : 'might have had',
        'mispell' : 'misspell',
        'mispelling' : 'misspelling',
        'mispellings' : 'misspellings',
        'mkae' : 'make',
        'mkaes' : 'makes',
        'mkaing' : 'making',
        'moeny' : 'money',
        'morgage' : 'mortgage',
        'mroe' : 'more',
        'msot' : 'most',
        'must of been' : 'must have been',
        'must of had' : 'must have had',
        'mysefl' : 'myself',
        'myu' : 'my',
        'necassarily' : 'necessarily',
        'necassary' : 'necessary',
        'neccessarily' : 'necessarily',
        'neccessary' : 'necessary',
        'necesarily' : 'necessarily',
        'necesary' : 'necessary',
        'negotiaing' : 'negotiating',
        'nkow' : 'know',
        'nothign' : 'nothing',
        'nver' : 'never',
        'nwe' : 'new',
        'nwo' : 'now',
        'obediant' : 'obedient',
        'ocasion' : 'occasion',
        'occassion' : 'occasion',
        'occured' : 'occurred',
        'occurence' : 'occurrence',
        'occurrance' : 'occurrence',
        'ocur' : 'occur',
        'oeprator' : 'operator',
        'ofits' : 'of its',
        'oft he' : 'of the',
        'ofthe' : 'of the',
        'oging' : 'going',
        'ohter' : 'other',
        'omre' : 'more',
        'oneof' : 'one of',
        'onepoint' : 'one point',
        'ont he' : 'on the',
        'onthe' : 'on the',
        'onyl' : 'only',
        'oppasite' : 'opposite',
        'opperation' : 'operation',
        'oppertunity' : 'opportunity',
        'opposate' : 'opposite',
        'opposible' : 'opposable',
        'opposit' : 'opposite',
        'oppotunities' : 'opportunities',
        'oppotunity' : 'opportunity',
        'orginization' : 'organization',
        'orginized' : 'organized',
        'otehr' : 'other',
        'otu' : 'out',
        'outof' : 'out of',
        'overthe' : 'over the',
        'owrk' : 'work',
        'owuld' : 'would',
        'oxident' : 'oxidant',
        'papaer' : 'paper',
        'parliment' : 'parliament',
        'partof' : 'part of',
        'paymetn' : 'payment',
        'paymetns' : 'payments',
        'pciture' : 'picture',
        'peice' : 'piece',
        'peices' : 'pieces',
        'peolpe' : 'people',
        'peopel' : 'people',
        'percentof' : 'percent of',
        'percentto' : 'percent to',
        'performence' : 'performance',
        'perhasp' : 'perhaps',
        'perhpas' : 'perhaps',
        'permanant' : 'permanent',
        'perminent' : 'permanent',
        'personalyl' : 'personally',
        'pleasent' : 'pleasant',
        'poeple' : 'people',
        'porblem' : 'problem',
        'porblems' : 'problems',
        'porvide' : 'provide',
        'possable' : 'possible',
        'postition' : 'position',
        'potentialy' : 'potentially',
        'pregnent' : 'pregnant',
        'presance' : 'presence',
        'probelm' : 'problem',
        'probelms' : 'problems',
        'prominant' : 'prominent',
        'psoition' : 'position',
        'ptogress' : 'progress',
        'puting' : 'putting',
        'pwoer' : 'power',
        'quater' : 'quarter',
        'quaters' : 'quarters',
        'quesion' : 'question',
        'quesions' : 'questions',
        'questioms' : 'questions',
        'questiosn' : 'questions',
        'questoin' : 'question',
        'quetion' : 'question',
        'quetions' : 'questions',
        'realyl' : 'really',
        'reccomend' : 'recommend',
        'reccommend' : 'recommend',
        'receieve' : 'receive',
        'recieve' : 'receive',
        'recieved' : 'received',
        'recieving' : 'receiving',
        'recomend' : 'recommend',
        'recomendation' : 'recommendation',
        'recomendations' : 'recommendations',
        'recomended' : 'recommended',
        'reconize' : 'recognize',
        'recrod' : 'record',
        'religous' : 'religious',
        'reluctent' : 'reluctant',
        'remeber' : 'remember',
        'reommend' : 'recommend',
        'representativs' : 'representatives',
        'representives' : 'representatives',
        'represetned' : 'represented',
        'represnt' : 'represent',
        'reserach' : 'research',
        'resollution' : 'resolution',
        'resorces' : 'resources',
        'respomd' : 'respond',
        'respomse' : 'response',
        'responce' : 'response',
        'responsability' : 'responsibility',
        'responsable' : 'responsible',
        'responsibile' : 'responsible',
        'responsiblity' : 'responsibility',
        'restaraunt' : 'restaurant',
        'restuarant' : 'restaurant',
        'reult' : 'result',
        'reveiw' : 'review',
        'reveiwing' : 'reviewing',
        'rumers' : 'rumors',
        'rwite' : 'write',
        'rythm' : 'rhythm',
        'saidhe' : 'said he',
        'saidit' : 'said it',
        'saidt he' : 'said the',
        'saidthat' : 'said that',
        'saidthe' : 'said the',
        'scedule' : 'schedule',
        'sceduled' : 'scheduled',
        'secratary' : 'secretary',
        'sectino' : 'section',
        'seh' : 'she',
        'selectoin' : 'selection',
        'sentance' : 'sentence',
        'separeate' : 'separate',
        'seperate' : 'separate',
        'sercumstances' : 'circumstances',
        'shcool' : 'school',
        'she\;ll' : 'she\'ll',
        'shesaid' : 'she said',
        'shineing' : 'shining',
        'shiped' : 'shipped',
        'shoudl' : 'should',
        'shoudln\'t' : 'shouldn\'t',
        'should of been' : 'should have been',
        'should of had' : 'should have had',
        'shouldent' : 'shouldn\'t',
        'shouldn\;t' : 'shouldn\'t',
        'shouldnt' : 'shouldn\'t',
        'showinf' : 'showing',
        'signifacnt' : 'significant',
        'simalar' : 'similar',
        'similiar' : 'similar',
        'simpyl' : 'simply',
        'sincerly' : 'sincerely',
        'sitll' : 'still',
        'smae' : 'same',
        'smoe' : 'some',
        'soem' : 'some',
        'sohw' : 'show',
        'soical' : 'social',
        'somethign' : 'something',
        'someting' : 'something',
        'somewaht' : 'somewhat',
        'somthing' : 'something',
        'somtimes' : 'sometimes',
        'sot hat' : 'so that',
        'soudn' : 'sound',
        'soudns' : 'sounds',
        'speach' : 'speech',
        'specificaly' : 'specifically',
        'specificalyl' : 'specifically',
        'statment' : 'statement',
        'statments' : 'statements',
        'stnad' : 'stand',
        'stopry' : 'story',
        'stoyr' : 'story',
        'stpo' : 'stop',
        'strentgh' : 'strength',
        'stroy' : 'story',
        'struggel' : 'struggle',
        'strugle' : 'struggle',
        'studnet' : 'student',
        'successfull' : 'successful',
        'successfuly' : 'successfully',
        'successfulyl' : 'successfully',
        'sucess' : 'success',
        'sucessfull' : 'successful',
        'sufficiant' : 'sufficient',
        'suposed' : 'supposed',
        'suppossed' : 'supposed',
        'suprise' : 'surprise',
        'suprised' : 'surprised',
        'swiming' : 'swimming',
        'tahn' : 'than',
        'taht' : 'that',
        'talekd' : 'talked',
        'talkign' : 'talking',
        'tath' : 'that',
        'tecnical' : 'technical',
        'teh' : 'the',
        'tehy' : 'they',
        'tellt he' : 'tell the',
        'termoil' : 'turmoil',
        'tghe' : 'the',
        'tghis' : 'this',
        'thansk' : 'thanks',
        'thats' : 'that\'s',
        'thatt he' : 'that the',
        'thatthe' : 'that the',
        'thecompany' : 'the company',
        'thefirst' : 'the first',
        'thegovernment' : 'the government',
        'their are' : 'there are',
        'their is' : 'there is',
        'themself' : 'themselves',
        'themselfs' : 'themselves',
        'thenew' : 'the new',
        'there\'s is' : 'theirs is',
        'theri' : 'their',
        'thesame' : 'the same',
        'thetwo' : 'the two',
        'they\'re are' : 'there are',
        'they\'re is' : 'there is',
        'they\;l' : 'they\'ll',
        'they\;ll' : 'they\'ll',
        'they\;r' : 'they\'re',
        'they\;re' : 'they\'re',
        'they\;v' : 'they\'ve',
        'they\;ve' : 'they\'ve',
        'theyll' : 'they\'ll',
        'theyve' : 'they\'ve',
        'thgat' : 'that',
        'thge' : 'the',
        'thier' : 'their',
        'thigsn' : 'things',
        'thisyear' : 'this year',
        'thna' : 'than',
        'thne' : 'then',
        'thnig' : 'thing',
        'thnigs' : 'things',
        'threatend' : 'threatened',
        'thsi' : 'this',
        'thsoe' : 'those',
        'thta' : 'that',
        'tihs' : 'this',
        'timne' : 'time',
        'tiogether' : 'together',
        'tje' : 'the',
        'tjhe' : 'the',
        'tkae' : 'take',
        'tkaes' : 'takes',
        'tkaing' : 'taking',
        'tlaking' : 'talking',
        'todya' : 'today',
        'togehter' : 'together',
        'toldt he' : 'told the',
        'tomorow' : 'tomorrow',
        'tongiht' : 'tonight',
        'tonihgt' : 'tonight',
        'totaly' : 'totally',
        'totalyl' : 'totally',
        'tothe' : 'to the',
        'towrad' : 'toward',
        'traditionalyl' : 'traditionally',
        'transfered' : 'transferred',
        'truely' : 'truly',
        'truley' : 'truly',
        'tryed' : 'tried',
        'tthe' : 'the',
        'tyhat' : 'that',
        'tyhe' : 'the',
        'udnerstand' : 'understand',
        'understnad' : 'understand',
        'undert he' : 'under the',
        'unliek' : 'unlike',
        'unpleasently' : 'unpleasantly',
        'untilll' : 'until',
        'useing' : 'using',
        'usualyl' : 'usually',
        'veyr' : 'very',
        'virtualyl' : 'virtually',
        'vrey' : 'very',
        'vulnerible' : 'vulnerable',
        'wa snot' : 'was not',
        'waht' : 'what',
        'warrent' : 'warrant',
        'wasnt' : 'wasn\'t',
        'watn' : 'want',
        'we\;d' : 'we\'d',
        'we\;ll' : 'we\'ll',
        'we\;re' : 'we\'re',
        'we\;ve' : 'we\'ve',
        'wehn' : 'when',
        'wern\'t' : 'weren\'t',
        'werre' : 'were',
        'what\;s' : 'what\'s',
        'whcih' : 'which',
        'whent he' : 'when the',
        'where\;s' : 'where\'s',
        'wherre' : 'where',
        'whic' : 'which',
        'whicht he' : 'which the',
        'whihc' : 'which',
        'who\;s' : 'who\'s',
        'who\;ve' : 'who\'ve',
        'whta' : 'what',
        'wief' : 'wife',
        'wierd' : 'weird',
        'wihch' : 'which',
        'wiht' : 'with',
        'will of been' : 'will have been',
        'will of had' : 'will have had',
        'willbe' : 'will be',
        'windoes' : 'windows',
        'witha' : 'with a',
        'withe' : 'with',
        'witht he' : 'with the',
        'withthe' : 'with the',
        'wiull' : 'will',
        'wnat' : 'want',
        'wnated' : 'wanted',
        'wnats' : 'wants',
        'wo\'nt' : 'won\'t',
        'woh' : 'who',
        'wohle' : 'whole',
        'wokr' : 'work',
        'won\;t' : 'won\'t',
        'woudl' : 'would',
        'woudln\'t' : 'wouldn\'t',
        'would of been' : 'would have been',
        'would of had' : 'would have had',
        'wouldbe' : 'would be',
        'wouldn\;t' : 'wouldn\'t',
        'wouldnt' : 'wouldn\'t',
        'wriet' : 'write',
        'writting' : 'writing',
        'wrod' : 'word',
        'wroet' : 'wrote',
        'wroking' : 'working',
        'wtih' : 'with',
        'wuould' : 'would',
        'wya' : 'way',
        'yera' : 'year',
        'yeras' : 'years',
        'yersa' : 'years',
        'yoiu' : 'you',
        'you\'re own' : 'your own',
        'you\;d' : 'you\'d',
        'you\;re' : 'you\'re',
        'youare' : 'you are',
        'your a' : 'you\'re a',
        'your an' : 'you\'re an',
        'your her' : 'you\'re her',
        'your here' : 'you\'re here',
        'your his' : 'you\'re his',
        'your my' : 'you\'re my',
        'your the' : 'you\'re the',
        'your their' : 'you\'re their',
        'your your' : 'you\'re your',
        'youve' : 'you\'ve',
        'ytou' : 'you',
        'yuo' : 'you',
        'yuor' : 'your',}

  def clean(self,words):
     cleaned = []
     for word in words:
       if word in self.abbr:
         word = self.abbr[word] 
       if word in self.spell:
         word = self.spell[word] 
       cleaned.append(word)
     return cleaned

def chat_hook(word, word_eol, userdata):
        #xchat.prnt("This is word: " + `word`)
        words = wordcleanser().clean(word[3:])
        #xchat.prnt("This is words: " + `words`)
        XCHAT_FESTIVAL.say(' '.join(words))
        return xchat.EAT_NONE

global XCHAT_FESTIVAL
XCHAT_FESTIVAL=festival()
XCHAT_FESTIVAL.say('speech activated')
xchat.hook_server("PRIVMSG", chat_hook)

# /load /home/jbruce/tmp/xchat-speak/xchat-speak.py
# /unload /home/jbruce/tmp/xchat-speak/xchat-speak.py


